[package]
name = "fcpeg"
version = "0.1.0"
edition = "2021"

[features]
js = []

[dependencies]
cons-util = { path = "C:/Users/Garnet3106/Desktop/Media/Docs/Repos/cons-util" }
num-traits = "0"
regex = "1"
tokio = { version = "1", features = ["full"] }
wasm-bindgen = "0"
